"""Enums for job lifecycle and status mapping."""

from enum import StrEnum


class JobState(StrEnum):
    RECEIVED_FROM_SONARR = "RECEIVED_FROM_SONARR"
    VALIDATING = "VALIDATING"
    SUBMITTED_TO_TORBOX = "SUBMITTED_TO_TORBOX"
    WAITING_FOR_TORBOX = "WAITING_FOR_TORBOX"
    TORBOX_READY = "TORBOX_READY"
    REFRESHING_WEBDAV = "REFRESHING_WEBDAV"
    WEBDAV_VISIBLE = "WEBDAV_VISIBLE"
    CREATING_SYMLINKS = "CREATING_SYMLINKS"
    READY_FOR_IMPORT = "READY_FOR_IMPORT"
    IMPORTED_OPTIONAL_DETECTED = "IMPORTED_OPTIONAL_DETECTED"
    FAILED = "FAILED"
    NEEDS_ATTENTION = "NEEDS_ATTENTION"


TERMINAL_STATES: set[JobState] = {
    JobState.READY_FOR_IMPORT,
    JobState.IMPORTED_OPTIONAL_DETECTED,
    JobState.FAILED,
}
